### ISSUE TITLE
Change the OpenInBrowser parameter

### ISSUE THREAD

**Issue by stefanstranger** [PowerShell/Phosphor#27]
Currently the Show-Module Cmdlet has a OpenInBrowser parameter to have Phosphor being opened in a Browser. Default the Phosphor UI is being opened. 

I suggest we change the Parameter name to ShowInBrowser just like we have -ShowWindow for the Get-Help Cmdlet.

/Stefan

**Comment by daviwil** [comment]
Good idea!
